Redforma\Reviews\Domain\Model\Company\Company:
    type: entity
    table: rf_company
    indexes:
        fk_company_creator:
            columns:
                - creator_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 80
            options:
                fixed: false
                default: ''
        slug:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
        ruc:
            type: string
            nullable: true
            length: 11
            options:
                fixed: false

        numReviews:
            type: integer
            nullable: true
            options:
               unsigned: false
               default: '0'
            column: num_reviews
        numStats:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: num_stats
        numFavs:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: num_favs
        image:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        banner:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        isFeatured:
            type: boolean
            nullable: true
            options:
                default: '0'
            column: featured
        state:
            type: boolean
            nullable: true
            options:
                default: '1'
    embedded:
        contactInfo:
          class: ContactInformation
          columnPrefix: false

    manyToMany:
        categories:
          orphanRemoval: true
          cascade: ["all"]
          targetEntity: Category
          joinTable:
            name: rf_company_categories_group
            joinColumns:
              company_id:
                referencedColumnName: id
            inverseJoinColumns:
              category_id:
                referencedColumnName: id
                unique: true
    manyToOne:
        creator:
            targetEntity: Redforma\Identity\Domain\Model\User\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                creator_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
