app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_config:
    resource: "@AppBundle/Resources/config/routes.yml"
    type: ~

api:
    resource: "@ApiBundle/Controller"
    type:     annotation
    prefix: /api
