parameters:
  hi: Andy

services:

    ## Services
    user.identity:
      class: Redforma\Identity\Application\Service\UserService
      arguments: ['@user.repository', '@auth.authentifier', '@auth.encryption']

    auth.encryption:
      class: Redforma\Identity\Infrastructure\Service\RawEncryptionService

    auth.authentifier:
      class: Redforma\Identity\Infrastructure\Service\Auth\SessionAuthentifier
      arguments: ['@session', '@user.repository', '@auth.encryption']

    ## Repositories
    user.repository:
      class: Redforma\Identity\Infrastructure\Persistence\Doctrine\DoctrineUserRepository
      arguments: [Redforma\Identity\Domain\Model\User\User, '@doctrine.orm.entity_manager']
