parameters:
    company_num_pagination: 20

services:

    ## Services
    company.service:
      class: Redforma\Reviews\Application\Service\CompanyService
      arguments: ['@company.repository', '@company.category.repository']

    user.identity:
      class: Redforma\Identity\Application\Service\UserService
      arguments: ['@user.repository', '@user.role.repository', '@auth.authentifier', '@auth.encryption']

    auth.encryption:
      class: Redforma\Identity\Infrastructure\Service\RawEncryptionService

    auth.authentifier:
      class: Redforma\Identity\Infrastructure\Service\Auth\SessionAuthentifier
      arguments: ['@session', '@user.repository', '@auth.encryption']

    ## Repositories
    user.repository:
      class: Redforma\Identity\Infrastructure\Persistence\Doctrine\DoctrineUserRepository
      arguments: [Redforma\Identity\Domain\Model\User\User, '@doctrine.orm.entity_manager']

    user.role.repository:
        class: Redforma\Identity\Infrastructure\Persistence\Doctrine\DoctrineRoleRepository
        arguments: [Redforma\Identity\Domain\Model\User\Role, '@doctrine.orm.entity_manager']

    company.repository:
        class: Redforma\Reviews\Infrastructure\Persistence\Doctrine\DoctrineCompanyRepository
        arguments: [Redforma\Reviews\Domain\Model\Company\Company, '@doctrine.orm.entity_manager']

    company.category.repository:
        class: Redforma\Reviews\Infrastructure\Persistence\Doctrine\DoctrineCategoryRepository
        arguments: [Redforma\Reviews\Domain\Model\Company\Category, '@doctrine.orm.entity_manager']