Redforma\Reviews\Domain\Model\Company\Category:
    type: entity
    table: rf_company_category
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 80
            options:
                fixed: false
        state:
            type: boolean
            nullable: true
            options:
                default: '1'
    lifecycleCallbacks: {  }
