homepage:
  path: /
  defaults:  { _controller: AppBundle:Home:index }

login:
  path: /user/login
  defaults: { _controller: AppBundle:User:login }

logout:
  path: /user/llgout
  defaults: { _controller: AppBundle:User:logout }

register:
  path: /user/register
  defaults: { _controller: AppBundle:User:register }

companies:
  path: /empresas/{page}
  defaults: { _controller: AppBundle:Company:index, page: 1 }
  requirements:
      page: \d+
