Redforma\Identity\Domain\Model\User\Role:
    type: entity
    table: rf_user_role
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
                default: ''
    lifecycleCallbacks: {  }
