Redforma\Identity\Domain\Model\User\Document:
    type: embeddable
    fields:
       type:
           type: string
           nullable: true
           length: 10
           options:
               fixed: true
           column: document_type
       number:
           type: string
           nullable: false
           length: 16
           options:
               fixed: true
               default: ''
           column: document_number
